### ISSUE TITLE
default accent

### ISSUE THREAD

**Issue by raulmaciascam** [tcz/rotary-gpt#4]
hi, how can I change the default accent on the code?

**Comment by tcz** [comment]
Yes, changing this line

    self.target_host = "polly.eu-west-1.amazonaws.com"

Should change the region. I guess it could have been a parameter.

Regarding the voice, indeed, change this line:

    default_voice = "Daniel"

It's important that you need to pick a voice that supports Neural Voice. Here's the full list:
https://docs.aws.amazon.com/polly/latest/dg/voicelist.html
