### ISSUE TITLE
Connecting to virtual PBX

### ISSUE THREAD

**Issue by AleksanderDanilian** [tcz/rotary-gpt#7]
Hi!

First of all, great work :)

I have a question - is it possible to use this sip server to connect to VPBX? So that several people could call simultaneously to PBX, and some of them, who would like to talk to assistant, would be connected to this sip client?

I would also like to know, if it is possible to try out your solution with regular mobile phone? I assume, I need to install some software first. 

Thanks!

**Comment by tcz** [comment]
Thank you!

In theory, the SIP server can handle an incoming call coming from anywhere, but the implementation is very bare-bones, made for the Grandstream specifically, and while it might work with calls coming from other SIP devices, it's not a guarantee. Worth a test though.
